### ISSUE TITLE
ormll.f90 fails to compile on alma 8

### ISSUE THREAD

**Issue by administratorte** [harrelfe/rms#163]
R 4.5.1, native alma 8 compiler:

using C compiler: ‘gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-26)’
using Fortran compiler: ‘GNU Fortran (GCC) 8.5.0 20210514 (Red Hat 8.5.0-26)’

gcc -I"/opt/R/4.5.1/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -c init.c -o init.o
gfortran  -fpic  -g -O2  -c  lrmll.f90 -o lrmll.o
gfortran  -fpic  -g -O2  -c mlmats.f -o mlmats.o
gfortran  -fpic  -g -O2  -c  ormll.f90 -o ormll.o
ormll.f90:373:48:

             il = findloc(row(1 : ne), j, mask = (col(1 : ne) == j2))
                                                1
Error: Keyword argument requires explicit interface for procedure ‘findloc’ at (1)
ormll.f90:373:17:

             il = findloc(row(1 : ne), j, mask = (col(1 : ne) == j2))
                 1
Error: Function ‘findloc’ at (1) has no IMPLICIT type
make: *** [/opt/R/4.5.1/lib/R/etc/Makeconf:229: ormll.o] Error 1
ERROR: compilation failed for package ‘rms’
* removing ‘/opt/R/4.5.1/lib/R/library/rms’

Setting -std to different values shows no change.

Later versions of the compiler (different machine: native debian 12.2; same machine: a built-from-source gcc 12.5) seem to be ok.

I can play games until it builds with 12.5 and even loads properly, but anything that depends on it needs to be rebuilt and so on.
It would be much easier if this would compile with the native compiler.  An upgrade to the OS is in the works but wasn't planned
for now.

Any help greatly appreciated.

Cheers.

**Comment by harrelfe** [comment]
That's a new one for me.  It sounds as if the old compiler did not fully implement findloc as a generic.  Unless you know of a declaration I can add to the code that is compiler-agnostic I don't know what to do.
